#!/bin/bash

# script name: frontend me
# description: whenever I am learning about frontend related stuff, I have
# to keep creating same repo skeleton over and over. This script eliminates and
# automates that.

cd ~/Desktop

# take command line argument and create a main dir named after the argument
cd $1  #this is command arg 1 because 0 is filename

# create the necessary meta repo files and directories such as
# .gitignore , docs/ , tests/ , branding/ , images/ ... etc.
mkdir branding
cd branding
touch foo.jpg
cd ..

mkdir tests
cd tests
touch test_foo.html  # selenium or some other testing shit
cd ..

mkdir docs
cd docs
touch index.md
cd ..

mkdir dev-cycle
cd dev-cycle
touch README.md
cd ..

touch .gitignore

echo "

# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
lerna-debug.log*

# Diagnostic reports (https://nodejs.org/api/report.html)
report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage
*.lcov

# nyc test coverage
.nyc_output

# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# Bower dependency directory (https://bower.io/)
bower_components

# node-waf configuration
.lock-wscript

# Compiled binary addons (https://nodejs.org/api/addons.html)
build/Release

# Dependency directories
node_modules/
jspm_packages/

# TypeScript v1 declaration files
typings/

# TypeScript cache
*.tsbuildinfo

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Microbundle cache
.rpt2_cache/
.rts2_cache_cjs/
.rts2_cache_es/
.rts2_cache_umd/

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variables file
.env
.env.test

# parcel-bundler cache (https://parceljs.org/)
.cache

# Next.js build output
.next

# Nuxt.js build / generate output
.nuxt
dist

# Gatsby files
.cache/
# Comment in the public line in if your project uses Gatsby and *not* Next.js
# https://nextjs.org/blog/next-9-1#public-directory-support
# public

# vuepress build output
.vuepress/dist

# Serverless directories
.serverless/

# FuseBox cache
.fusebox/

# DynamoDB Local files
.dynamodb/

# TernJS port file
.tern-port
" > .gitignore


touch AUTHORS
echo "Demir Antay (demir99antay@gmail.com)" >> AUTHORS

touch requirements.txt

# create the necessary html dirs/ and files with content inside
mkdir static
cd static
mkdir js
cd js
touch foo.js
cd ..

mkdir css
cd css
touch base.css
touch navigation.css
touch content.css
touch footer.css
echo "
/* Base CSS File ----- */

/*
  Color Pallette
  --------------
  Dark Red:     #C0392B
  Light Red:    #E74C3C

  Dark Purple:  #8E44AD
  Light Purple: #9B59B6

  Dark Blue:    #2980B9
  Light Blue:   #3498DB

  Dark Green:   #27AE60
  Light Green:  #2ECC71

  Dark Yellow:  #F1C40F
  Light Yellow: #F7DC6F

  Dark Orange:  #E67E22
  Light Orange: #F39C12

  Dark Grey:    #7F8C8D
  Light Grey:   #CACFD2

  Dark: Navy:   #2C3E50
  Light: Navy:  #34495E

  Black:        #2C3135
  FORM BORDERS: #EAEDED
*/

* {
  margin: 0;
  padding: 0;
  font-family: "Roboto";
}

h1, h2, h3, h4, h5, h6 {
  font-family: "Roboto";
}

p {
  font-family: "Roboto";
}

/* Mobile Small  --------------------------------------------------------- */
@media screen and (min-width: 0px) and (max-width: 320px) {

}


/* Mobile Medium  --------------------------------------------------------- */
@media screen and (min-width: 321px) and (max-width: 375px) {

}


/* Mobile Large - --------------------------------------------------------- */
@media screen and (min-width: 376px) and (max-width: 425px) {

}


/* Tablet - --------------------------------------------------------------- */
@media screen and (min-width: 426px) and (max-width: 768px) {

}


/* Laptop ------------------------------------------------------------------ */
@media screen and (min-width: 769px) and (max-width: 1024px) {

}


/* Laptop Large -------------------------------------------------------------*/
@media screen and (min-width: 1025px) and (max-width: 1440px) {

}


/* 4K Large Desktop ------------------------------------------------------- */
@media screen and (min-width: 1441px) {

}
" > base.css

echo "
/* Navigation CSS File ----- */

/* Mobile Small  --------------------------------------------------------- */
@media screen and (min-width: 0px) and (max-width: 320px) {

}


/* Mobile Medium  --------------------------------------------------------- */
@media screen and (min-width: 321px) and (max-width: 375px) {

}


/* Mobile Large - --------------------------------------------------------- */
@media screen and (min-width: 376px) and (max-width: 425px) {

}


/* Tablet - --------------------------------------------------------------- */
@media screen and (min-width: 426px) and (max-width: 768px) {

}


/* Laptop ------------------------------------------------------------------ */
@media screen and (min-width: 769px) and (max-width: 1024px) {

}


/* Laptop Large -------------------------------------------------------------*/
@media screen and (min-width: 1025px) and (max-width: 1440px) {

}


/* 4K Large Desktop ------------------------------------------------------- */
@media screen and (min-width: 1441px) {

}

" > navigation.css

echo "
/* Content CSS File ----- */

/* Mobile Small  --------------------------------------------------------- */
@media screen and (min-width: 0px) and (max-width: 320px) {

}


/* Mobile Medium  --------------------------------------------------------- */
@media screen and (min-width: 321px) and (max-width: 375px) {

}


/* Mobile Large - --------------------------------------------------------- */
@media screen and (min-width: 376px) and (max-width: 425px) {

}


/* Tablet - --------------------------------------------------------------- */
@media screen and (min-width: 426px) and (max-width: 768px) {

}


/* Laptop ------------------------------------------------------------------ */
@media screen and (min-width: 769px) and (max-width: 1024px) {

}


/* Laptop Large -------------------------------------------------------------*/
@media screen and (min-width: 1025px) and (max-width: 1440px) {

}


/* 4K Large Desktop ------------------------------------------------------- */
@media screen and (min-width: 1441px) {

}

" > content.css

echo "
/* Footer CSS File ----- */

/* Mobile Small  --------------------------------------------------------- */
@media screen and (min-width: 0px) and (max-width: 320px) {

}


/* Mobile Medium  --------------------------------------------------------- */
@media screen and (min-width: 321px) and (max-width: 375px) {

}


/* Mobile Large - --------------------------------------------------------- */
@media screen and (min-width: 376px) and (max-width: 425px) {

}


/* Tablet - --------------------------------------------------------------- */
@media screen and (min-width: 426px) and (max-width: 768px) {

}


/* Laptop ------------------------------------------------------------------ */
@media screen and (min-width: 769px) and (max-width: 1024px) {

}


/* Laptop Large -------------------------------------------------------------*/
@media screen and (min-width: 1025px) and (max-width: 1440px) {

}


/* 4K Large Desktop ------------------------------------------------------- */
@media screen and (min-width: 1441px) {

}
" > footer.css

cd ..

mkdir images
cd ..

mkdir templates
cd templates
touch index.html

echo '
<!doctype html>
<html>

<head>
  <title> ... </title>

  <!-- Meta Info -->
  <meta charset="utf-8" />
  <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="demir antay, Demir Antay, @demirantay" />

  <!-- FAVICON -->
  <link rel="icon" href="" />

  <!-- GOOGLE FONTS -->
  <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lato:300,700|Prata" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Literata&display=swap" rel="stylesheet">

  <!-- FONT AWSOME -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <!-- BASE CSS LINKS -->
  <link rel="stylesheet" type="text/css" href="../static/css/base.css" />
  <link rel="stylesheet" type="text/css" href="../static/css/navigation.css" />
  <link rel="stylesheet" type="text/css" href="../static/css/content.css" />
  <link rel="stylesheet" type="text/css" href="../static/css/footer.css" />

  <!-- SPECIFIC CSS LINKS -->


</head>

<body>

  <!-- NAVIGATION -->


  <!-- CONTENT -->

  <!-- FOOTER -->

</body>

</html>
' > index.html

cd ..

script_status="Build successful!"

echo $script_status
